### ISSUE TITLE
Task 22.1: Logo Creation

### ISSUE THREAD

**Issue by wmilun** [paceuniversity/cs389f2022team1#40]
Create logo using photoshop

**Comment by dg52718n** [comment]
![TWIRIAizZFU(1)](https://user-images.githubusercontent.com/63370996/200952389-0d8a542c-9c3d-4b55-b6ed-dc255502d8ea.png)

**Comment by dg52718n** [comment]
![Image](https://user-images.githubusercontent.com/63370996/200953148-f3dd1b9e-4723-464d-9934-ac77022a7afc.png)
